{{ if .Values.alert_trigger }}
---
apiVersion: triggers.tekton.dev/v1beta1	
kind: TriggerTemplate
metadata:
  name: ct-alert-trigger-template
spec:
  params:
    - name: application_name
      description: The name of the application
    - name: version
      description: version of the application
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ct-pipeline-
      spec:
        pipelineRef:
          name: ct-alert-pipeline
        params:
          - name: APPLICATION_NAME
            value: $(tt.params.application_name)
          - name: VERSION
            value: $(tt.params.version)
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace
        - name: model-workspace
          persistentVolumeClaim:
            claimName: jukebox-model-pvc
{{- end }}