---
apiVersion: v2
description: A Helm chart for deploying Tekton Pipeline that handles post deployment tasks 🐈
name: post-deployment-pipeline
version: 0.0.1
home: https://rhoai-mlops.github.io/mlops/
maintainers:
  - name: RHRolun
  - name: rcarrata
  - name: ckavili